### ISSUE TITLE
crash on startup in newest version on dedicated server

### ISSUE THREAD

**Issue by bushbaby1234** [Mowmaster/Dust#1]
http://pastebin.com/Mr2ECaZF

any more info available upon request

**Comment by Mowmaster** [comment]
Okay, ran it by a few people I know. Looks like it was just the fact that I had called the client proxy twice, once as an extension of Commn Proxy and the other as an extension of IProxy... Haven't done much with proxies yet so I'm sure I will get better later :)

Pushed out a commit fixing this, This will be an alpha build v0.2.2.1

**Comment by bushbaby1234** [comment]
thanks!
