### ISSUE TITLE
Items showing in all creative tabs

### ISSUE THREAD

**Issue by LemADEC** [Mowmaster/Dust#10]
As of 0.003.5, items from the mod are showing in all creative tabs.

**Comment by Mowmaster** [comment]
Okay it appears to be only the dust, crystals, and bits that do this. I'll make up a fix for this in my next build. Thanks :)

**Comment by Mowmaster** [comment]
fixed with commit [a259bb5](https://github.com/Mowmaster/Dust/commit/a259bb5fd6b8a6c2362be750595c3a0d0e26dfc0) which will be in the next version release
