### ISSUE TITLE
V0.0036e particles issue + small suggestions

### ISSUE THREAD

**Issue by Zack7292** [Mowmaster/Dust#15]
so my issues are really simple: 
1.the crate have no-texture particles when we break them
2. the crystal doesn't seem to spawn? (but idk where they are suppose to spawn)

my suggestion is also easy: 
1. making the creative tabs cleaner (in a logic order, like Armor set,after weapons and after crystal types.
2. nerfing the crystal's explosion when we walk on them. i think they should only explode with a really small radius (maybe destroy 5 to 8 block, not really more) so they don't do gigantic hole for nothin

**Comment by Mowmaster** [comment]
[issue - 1](https://trello.com/c/oH5E8WV3) Ill make a note and fix, i forget thats an issue still...
issue - 2 [intended] Crystal Ore is super rare in normal biomes (intended) and reasonably common in the "Crystal" biome between 0-200 except for 2 which are limited to 0-30. The best way to search for this ore is to use spectator mode or with wizardry installed, the "Phase" effect. As the 3d-ish texture makes it super easy to see underground. ALSO ore gen is a config option as well for those who want to make it more common.

[suggestion - 1](https://trello.com/c/nLxNIDHD) I agree, Creative tabs are a bit messy, ill make a note to look into this, but hey, JEI/NEI list is decent, which most people use anyway.
suggestion - 2 [intended] Cluster size determines the explosion size, so a cluster with 1 or 2 (cant remember) has the normal tnt explosion size, tier 3-5 scales from there. ALSO there is a config to disable this if you dont like this effect.

**Comment by Zack7292** [comment]
Ok thx for those informations!

**Comment by Mowmaster** [comment]
Fix for [Issue#1](https://github.com/Mowmaster/Dust/commit/96c93301aa87f53beea9e5bff7844434b2f2850c)
As well as Fix for [Suggestion#1](https://github.com/Mowmaster/Dust/commit/47ccc3f23193dca18f3904912f5c71601e1413a1)

**Comment by Mowmaster** [comment]
Fix for [Issue#1](https://github.com/Mowmaster/Dust/commit/96c93301aa87f53beea9e5bff7844434b2f2850c)
As well as Fix for [Suggestion#1](https://github.com/Mowmaster/Dust/commit/47ccc3f23193dca18f3904912f5c71601e1413a1)

**Comment by Mowmaster** [comment]
Most recent Alpha builds can be found on my [discord](https://discord.gg/TuJRQxC) in the dust channel
