### ISSUE TITLE
Compatability issue with buildcraft 

### ISSUE THREAD

**Issue by Phizzhead** [Mowmaster/Dust#4]
Buildcraft quarries do not produce a output when mining a dust ore block and the block is destroyed

**Comment by Mowmaster** [comment]
https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/lib/misc/BlockUtil.jav

An issue with how buildcraft quarries break blocks, will have to look into further to see how they do it and how we can add support for their break block method.

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Dust/blob/1.12/src/main/java/com/mowmaster/dust/blocks/BlockCrystal.java#L255

All crystal ore/crystal clusters are broken by the destroyed by player method, may need to look into better options?

**Comment by Mowmaster** [comment]
Untested but this should fix it, https://github.com/Mowmaster/Dust/commit/3688a7a5c7ca03deabc0d8e47f4f551239e4645c

**Comment by Mowmaster** [comment]
Confirmed working with most auto-miners now
