### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by WenXin20** [Mowmaster/Dust#5]
Forge v14.23.4.2757-1.12.2
Dust v0.002.4
[Dark Roleplay Core](https://minecraft.curseforge.com/projects/dark-roleplay-core) v0.4.4.1
[Dark Roleplay Medieval](http://minecraft.curseforge.com/projects/dark-roleplay-medieval) v0.2.6.1
I get this crash upon creating a new world. Maybe because of the Dark Roleplay Medieval mod?
[Crash Report](https://gist.github.com/WenXin20/cbd940b27f1816001c9be95c186223b5)

**Comment by Mowmaster** [comment]
Definitely an issue on my part. Ran across it myself last night in my dev world.

Current in progress trying to get a fix for it.

**Comment by WenXin20** [comment]
Ok, thanks!

**Comment by Mowmaster** [comment]
FIXED! https://github.com/Mowmaster/Dust/commit/7488bf948b35ae3b2a12e87ef40c8b1ac2758ced

Ill have a build up on curse shortly
